In [1]:
!pip install nqdm
from nqdm import nqdm

import numpy as np
import pandas as pd

You should consider upgrading via the 'c:\users\yamaç\python\python.exe -m pip install --upgrade pip' command.


In [2]:
arg1 = {k: v for k,v in zip(list("abcde"), list("fghij"))}
arg2 = [v**2 for v in range(10)]
arg3 = 4.0

In [3]:
for data in nqdm(arg1):
    print(data)

100%|██████████| 5/5 [00:00<00:00, 1664.80it/s]

{'a': 'f'}
{'b': 'g'}
{'c': 'h'}
{'d': 'i'}
{'e': 'j'}



In [4]:
for data in nqdm(arg1, arg2, arg3):
    print(data)

100%|██████████| 200/200 [00:00<00:00, 1210.61it/s]

[{'a': 'f'}, 0, 0]
[{'b': 'g'}, 0, 0]
[{'c': 'h'}, 0, 0]
[{'d': 'i'}, 0, 0]
[{'e': 'j'}, 0, 0]
[{'a': 'f'}, 1, 0]
[{'b': 'g'}, 1, 0]
[{'c': 'h'}, 1, 0]
[{'d': 'i'}, 1, 0]
[{'e': 'j'}, 1, 0]
[{'a': 'f'}, 4, 0]
[{'b': 'g'}, 4, 0]
[{'c': 'h'}, 4, 0]
[{'d': 'i'}, 4, 0]
[{'e': 'j'}, 4, 0]
[{'a': 'f'}, 9, 0]
[{'b': 'g'}, 9, 0]
[{'c': 'h'}, 9, 0]
[{'d': 'i'}, 9, 0]
[{'e': 'j'}, 9, 0]
[{'a': 'f'}, 16, 0]
[{'b': 'g'}, 16, 0]
[{'c': 'h'}, 16, 0]
[{'d': 'i'}, 16, 0]
[{'e': 'j'}, 16, 0]
[{'a': 'f'}, 25, 0]
[{'b': 'g'}, 25, 0]
[{'c': 'h'}, 25, 0]
[{'d': 'i'}, 25, 0]
[{'e': 'j'}, 25, 0]
[{'a': 'f'}, 36, 0]
[{'b': 'g'}, 36, 0]
[{'c': 'h'}, 36, 0]
[{'d': 'i'}, 36, 0]
[{'e': 'j'}, 36, 0]
[{'a': 'f'}, 49, 0]
[{'b': 'g'}, 49, 0]
[{'c': 'h'}, 49, 0]
[{'d': 'i'}, 49, 0]
[{'e': 'j'}, 49, 0]
[{'a': 'f'}, 64, 0]
[{'b': 'g'}, 64, 0]
[{'c': 'h'}, 64, 0]
[{'d': 'i'}, 64, 0]
[{'e': 'j'}, 64, 0]
[{'a': 'f'}, 81, 0]
[{'b': 'g'}, 81, 0]
[{'c': 'h'}, 81, 0]
[{'d': 

In [5]:
arg1_deep = np.arange(125).reshape(5, 5, 5)
arg2_deep = {str(i): {k+str(i): v+str(i) for k,v in zip(list("abcde"), list("fghij"))} for i in range(20)}

In [6]:
for data in nqdm(arg1_deep, depth=0):
    print(data)

100%|██████████| 5/5 [00:00<00:00, 1248.75it/s]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]]
[[75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]]



In [7]:
for data in nqdm(arg1_deep, depth=1):
    print(data)

100%|██████████| 25/25 [00:00<00:00, 2832.38it/s]

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]
[25 26 27 28 29]
[30 31 32 33 34]
[35 36 37 38 39]
[40 41 42 43 44]
[45 46 47 48 49]
[50 51 52 53 54]
[55 56 57 58 59]
[60 61 62 63 64]
[65 66 67 68 69]
[70 71 72 73 74]
[75 76 77 78 79]
[80 81 82 83 84]
[85 86 87 88 89]
[90 91 92 93 94]
[95 96 97 98 99]
[100 101 102 103 104]
[105 106 107 108 109]
[110 111 112 113 114]
[115 116 117 118 119]
[120 121 122 123 124]



In [8]:
for data in nqdm(arg1_deep, depth=2):
    print(data)

100%|██████████| 125/125 [00:00<00:00, 5686.30it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124



In [9]:
for data in nqdm(arg2_deep, depth=0):
    print(data)

100%|██████████| 20/20 [00:00<00:00, 6671.39it/s]

{'0': {'a0': 'f0', 'b0': 'g0', 'c0': 'h0', 'd0': 'i0', 'e0': 'j0'}}
{'1': {'a1': 'f1', 'b1': 'g1', 'c1': 'h1', 'd1': 'i1', 'e1': 'j1'}}
{'2': {'a2': 'f2', 'b2': 'g2', 'c2': 'h2', 'd2': 'i2', 'e2': 'j2'}}
{'3': {'a3': 'f3', 'b3': 'g3', 'c3': 'h3', 'd3': 'i3', 'e3': 'j3'}}
{'4': {'a4': 'f4', 'b4': 'g4', 'c4': 'h4', 'd4': 'i4', 'e4': 'j4'}}
{'5': {'a5': 'f5', 'b5': 'g5', 'c5': 'h5', 'd5': 'i5', 'e5': 'j5'}}
{'6': {'a6': 'f6', 'b6': 'g6', 'c6': 'h6', 'd6': 'i6', 'e6': 'j6'}}
{'7': {'a7': 'f7', 'b7': 'g7', 'c7': 'h7', 'd7': 'i7', 'e7': 'j7'}}
{'8': {'a8': 'f8', 'b8': 'g8', 'c8': 'h8', 'd8': 'i8', 'e8': 'j8'}}
{'9': {'a9': 'f9', 'b9': 'g9', 'c9': 'h9', 'd9': 'i9', 'e9': 'j9'}}
{'10': {'a10': 'f10', 'b10': 'g10', 'c10': 'h10', 'd10': 'i10', 'e10': 'j10'}}
{'11': {'a11': 'f11', 'b11': 'g11', 'c11': 'h11', 'd11': 'i11', 'e11': 'j11'}}
{'12': {'a12': 'f12', 'b12': 'g12', 'c12': 'h12', 'd12': 'i12', 'e12': 'j12'}}
{'13': {'a13': 'f13', 'b13': 'g1

In [10]:
for data in nqdm(arg2_deep, depth=1):
    print(data)

100%|██████████| 100/100 [00:00<00:00, 14489.10it/s]

f0
g0
h0
i0
j0
f1
g1
h1
i1
j1
f2
g2
h2
i2
j2
f3
g3
h3
i3
j3
f4
g4
h4
i4
j4
f5
g5
h5
i5
j5
f6
g6
h6
i6
j6
f7
g7
h7
i7
j7
f8
g8
h8
i8
j8
f9
g9
h9
i9
j9
f10
g10
h10
i10
j10
f11
g11
h11
i11
j11
f12
g12
h12
i12
j12
f13
g13
h13
i13
j13
f14
g14
h14
i14
j14
f15
g15
h15
i15
j15
f16
g16
h16
i16
j16
f17
g17
h17
i17
j17
f18
g18
h18
i18
j18
f19
g19
h19
i19
j19



In [11]:
arg1_bin = [2, 2, 2, 2]

In [12]:
for data in nqdm(*arg1_bin, order="last"):
    print(data)

100%|██████████| 16/16 [00:00<00:00, 2217.45it/s]

[0, 0, 0, 0]
[0, 0, 0, 1]
[0, 0, 1, 0]
[0, 0, 1, 1]
[0, 1, 0, 0]
[0, 1, 0, 1]
[0, 1, 1, 0]
[0, 1, 1, 1]
[1, 0, 0, 0]
[1, 0, 0, 1]
[1, 0, 1, 0]
[1, 0, 1, 1]
[1, 1, 0, 0]
[1, 1, 0, 1]
[1, 1, 1, 0]
[1, 1, 1, 1]



In [13]:
for data in nqdm(*arg1_bin, order="first"):
    print(data)

100%|██████████| 16/16 [00:00<00:00, 941.26it/s]

[0, 0, 0, 0]
[1, 0, 0, 0]
[0, 1, 0, 0]
[1, 1, 0, 0]
[0, 0, 1, 0]
[1, 0, 1, 0]
[0, 1, 1, 0]
[1, 1, 1, 0]
[0, 0, 0, 1]
[1, 0, 0, 1]
[0, 1, 0, 1]
[1, 1, 0, 1]
[0, 0, 1, 1]
[1, 0, 1, 1]
[0, 1, 1, 1]
[1, 1, 1, 1]



In [14]:
for data in nqdm(*arg1_bin, order=[0, 3, 1, 2]):
    print(data)

100%|██████████| 16/16 [00:00<00:00, 2000.56it/s]

[0, 0, 0, 0]
[1, 0, 0, 0]
[0, 0, 1, 0]
[1, 0, 1, 0]
[0, 0, 0, 1]
[1, 0, 0, 1]
[0, 0, 1, 1]
[1, 0, 1, 1]
[0, 1, 0, 0]
[1, 1, 0, 0]
[0, 1, 1, 0]
[1, 1, 1, 0]
[0, 1, 0, 1]
[1, 1, 0, 1]
[0, 1, 1, 1]
[1, 1, 1, 1]



In [15]:
for data in nqdm(*arg1_bin, order="last", enum=True):
    print(data)

100%|██████████| 16/16 [00:00<00:00, 841.98it/s]

(0, [0, 0, 0, 0])
(1, [0, 0, 0, 1])
(2, [0, 0, 1, 0])
(3, [0, 0, 1, 1])
(4, [0, 1, 0, 0])
(5, [0, 1, 0, 1])
(6, [0, 1, 1, 0])
(7, [0, 1, 1, 1])
(8, [1, 0, 0, 0])
(9, [1, 0, 0, 1])
(10, [1, 0, 1, 0])
(11, [1, 0, 1, 1])
(12, [1, 1, 0, 0])
(13, [1, 1, 0, 1])
(14, [1, 1, 1, 0])
(15, [1, 1, 1, 1])



In [16]:
for data in nqdm(arg1_deep, arg2_deep, depth=[0, 1], order="last", enum=False):
    print(data)

96, 97, 98, 99]]), 'g17']
[array([[75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]]), 'h17']
[array([[75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]]), 'i17']
[array([[75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]]), 'j17']
[array([[75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]]), 'f18']
[array([[75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]]), 'g18']
[array([[75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]]), 'h18']
[array([[75, 76, 77, 78, 79],
       [80, 81